version: '3.7'
services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #   container_name: elasticsearch
  #   restart: unless-stopped
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     - 'discovery.type:single-node'
  #     - 'ES_JAVA_OPTS:-Xms2g -Xmx2g'
  #     - 'xpack.monitoring.enabled:true'
  #     - 'bootstrap.system_call_filter=false'
  #   networks:
  #     - elastic

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.15.0
  #   container_name: kibana
  #   restart: unless-stopped
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - 'ELASTICSEARCH_URL:http://elasticsearch:9200'
  #     - 'ELASTICSEARCH_HOST:elasticsearch'
  #     - 'ELASTICSEARCH_PORT:9200'
  #   networks:
  #     - elastic
  #   depends_on:
  #     - elasticsearch

  search-graphql:
    container_name: search-graphql
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - elastic
    ports:
      - 4001:4001
    environment:
      NODE_ENV: "development"
      PORT: 4001
    depends_on:
      - elasticsearch

networks:
  elastic:
    name: elastic
    driver: bridge
