version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

  search-graphql:
    container_name: search-graphql
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - elastic
    ports:
      - 4001:4001
    environment:
      NODE_ENV: "development"
      PORT: 4001
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
